import {
  MapPin,
  Vote,
  Trophy,
  Sparkles,
  Coffee,
  Atom,
  Landmark,
  Megaphone,
  HeartHandshake,
  GraduationCap,
  Car,
  Newspaper,
  Flag,
  ShieldCheck,
  Signpost,
  Star,
  Flower2,
  Mountain,
  Layers,
  Wrench,
  Sunset,
  MoonStar,
  Smile,
  Globe2,
  Users,
  Building,
  Medal,
  Clapperboard,
  Briefcase,
  IndianRupee,
  Cpu,
  HeartPulse,
  Earth,
  BookOpen,
  TrendingUp,
  Home,
  Apple,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

// Icon per category — the icon represents what the channel is about.
const ICON_MAP: Record<string, LucideIcon> = {
  local: MapPin,
  "election-2026": Vote,
  "ipl-2026": Trophy,
  "db-original": Sparkles,
  lifestyle: Coffee,
  science: Atom,
  "uttar-pradesh": Landmark,
  opinion: Megaphone,
  "jeevan-mantra": HeartHandshake,
  "jobs-education": GraduationCap,
  "tech-auto": Car,
  "top-news": Newspaper,
  national: Flag,
  "fake-news-expose": ShieldCheck,
  bihar: Signpost,
  "bhaskar-khaas": Star,
  madhurima: Flower2,
  "madhya-pradesh": Mountain,
  magazine: Layers,
  utility: Wrench,
  rajasthan: Sunset,
  rashifal: MoonStar,
  "happy-life": Smile,
  international: Globe2,
  women: Users,
  politics: Building,
  sports: Medal,
  entertainment: Clapperboard,
  business: Briefcase,
  finance: IndianRupee,
  technology: Cpu,
  health: HeartPulse,
  world: Earth,
  education: BookOpen,
  apple: Apple,
  "0": Home,
};

// Distinct brand colour per category — full-colour icons.
const COLOR_MAP: Record<string, string> = {
  local: "#2563eb",
  "election-2026": "#7c3aed",
  "ipl-2026": "#f59e0b",
  "db-original": "#ec4899",
  lifestyle: "#b45309",
  science: "#0891b2",
  "uttar-pradesh": "#f97316",
  opinion: "#ef4444",
  "jeevan-mantra": "#e11d48",
  "jobs-education": "#0d9488",
  "tech-auto": "#6366f1",
  "top-news": "#dc2626",
  national: "#2563eb",
  "fake-news-expose": "#059669",
  bihar: "#d97706",
  "bhaskar-khaas": "#f59e0b",
  madhurima: "#db2777",
  "madhya-pradesh": "#65a30d",
  magazine: "#8b5cf6",
  utility: "#64748b",
  rajasthan: "#ea580c",
  rashifal: "#7c3aed",
  "happy-life": "#facc15",
  international: "#0ea5e9",
  women: "#ec4899",
  politics: "#1e40af",
  sports: "#16a34a",
  entertainment: "#9333ea",
  business: "#f97316",
  finance: "#059669",
  technology: "#0891b2",
  health: "#e11d48",
  world: "#0ea5e9",
  education: "#2563eb",
  apple: "#111111",
  "0": "#f47216",
};

export default function CategoryIcon({
  slug,
  size = 16,
  color,
  className,
}: {
  slug: string | null | undefined;
  size?: number;
  color?: string;
  className?: string;
}) {
  const Icon = ICON_MAP[slug ?? ""] ?? Home;
  const fill = color ?? COLOR_MAP[slug ?? ""] ?? "#f47216";
  return <Icon size={size} color={fill} strokeWidth={2.1} className={className} style={{ flexShrink: 0 }} />;
}
